## These functions are useful in the inversion of square matrixes through the use of caching
## makeCacheMatrix will create a list from which cacheSolve can either solve and cache or retrieve cached data

## makeCacheMatrix creates a list whereby the cached matrix can be stored from an input matrix

makeCacheMatrix <- function (x = numeric()){   ## function accepts matrix, x, as an argument
                                               ## no restriction on matrix size,but solve() will 
					       ## display error message if matrix not square invertible 
											   
  mat <- NULL                           ##  mat will store inverse square
                                        ##resets to NULL for every function call
  
  get <- function() { x }               ## return original matrix
  
  setmat <- function(solve)             ## solves and stores the solved matrix by superassignment
  { mat <<- solve } 
  
  getmat <- function() { mat }          ## function to return cached matrix data
  
  list(get = get, setmat = setmat, getmat = getmat)  ## returns list with:              
                                                     ## matrix (get(x)), assignment function, 
						     ## and retrieval function
}


## cacheSolve will either retrieve or solve a matrix from the list generated by makeCacheMatrix

cacheSolve <- function (x, ...){ ## takes the list from makeCacheMatrix as an argument
                                 ## just a simple retrieval/solving function 
								 
  mat <- x$getmat()              ## reads the matrix from makeCacheMatrix list
  
  if(!is.null(mat)) {            ## if mat exists (cached, retrieves the matrix)
    message("Retrieving cached matrix data:...")
    mat
    return 
  }
  
  solver <- x$get()         ## else, retrieve input matrix
  
  mat <- solve(solver, ...) ##solves input matrix to inverse
  
  x$setmat(mat)             ## stores value in list from makeCacheMatrix
  
  mat                       ## return
}
